wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1654351690
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      4: 3.9.7
      5: 0.12.17
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 5
loss_function:
  desc: null
  value: BinaryCrossentropy
